export const UI_COLORS = {
  pageBg: '#F4FBFE',
  surface: '#FFFFFF',
  surfaceMuted: '#EAF6FB',
  surfaceSoft: '#F3FAFD',
  border: '#D5EAF1',
  borderSoft: '#E1F1F6',
  borderMuted: '#DDEDF4',
  textPrimary: '#0B1F2A',
  textSecondary: '#475569',  
  textMuted: '#64748B',    
  link: '#2BB5D6',
  linkPressed: '#1F9CB9',
  accent: '#2BB5D6',
  accentPressed: '#1F9CB9',
  accentSoft: 'rgba(43, 181, 214, 0.12)',
  accentBorder: '#9CDDEA',
  info: '#7AD9ED',
  warning: '#F59E0B',
  success: '#10B981',
  danger: '#EF4444',
  hint: '#B45309',
  hintBg: '#FFFBEB',
  hintBorder: '#FDE68A',
  leaderboard: {
    rank1: {
      border: '#E7CB62',
      badgeBg: '#FFF4C9',
      badgeText: '#A56E00',
      rankText: '#A56E00',
      cardBg: '#FFFDF2',
      stripeBg: '#F9EDB5',
      shadow: '#D4A11D',
    },
    rank2: {
      border: '#CAD5E4',
      badgeBg: '#EEF3FA',
      badgeText: '#4C617C',
      rankText: '#4C617C',
      cardBg: '#F7FAFF',
      stripeBg: '#E5EDF8',
      shadow: '#9BB3CC',
    },
    rank3: {
      border: '#E7C6AA',
      badgeBg: '#FFF0E4',
      badgeText: '#99540F',
      rankText: '#99540F',
      cardBg: '#FFF9F4',
      stripeBg: '#FCE3D0',
      shadow: '#D49B6C',
    },
    self: {
      border: '#78C9DE',
    },
    premium: {
      badgeBg: '#FFF3D6',
      badgeBorder: '#E7CB62',
      icon: '#B67B00',
      rowIcon: '#C79000',
    },
    skeleton: {
      border: '#E4EAF2',
      rowBg: '#FFFFFF',
      rank: '#DEE6F2',
      badge: '#E1E8F4',
      textMain: '#DEE6F2',
      textSub: '#E6EDF8',
      value: '#D9F2E5',
    },
  },
};

export const UI_TYPE_SCALE = {
  leaderboard: {
    title: 22,
    subtitle: 12,
    status: 11,
    columnHeader: 10,
    rowMeta: 11,
    rowName: 13,
    rowValue: 12,
  },
  marketDetails: {
    sectionTitle: 16,
    commentMeta: 11,
    commentBadge: 10,
    commentBody: 13,
    helper: 12,
  },
};

export const UI_SHADOWS = {
  soft: {
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  lift: {
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 4,
  },
};

export const UI_FONTS = {
  body: 'InterTight_400Regular',
  bodyBold: 'InterTight_700Bold',
  heading: 'SpaceGrotesk_700Bold',
  headingRegular: 'SpaceGrotesk_400Regular',
  mono: 'JetBrainsMono_400Regular',
  monoBold: 'JetBrainsMono_700Bold',
};
